### ISSUE TITLE
运行代码后还是无法回答长文本

### ISSUE THREAD

**Issue by Eren139** [datamllab/LongLM#14]
错误显示如下：
Token indices sequence length is longer than the specified maximum sequence length for this model (9556 > 4096). Running this sequence through the model will result in indexing errors

**Comment by Mooler0410** [comment]
This is a warning from HF to indicate that the output exceeds the original context window length. 

But if you check the output, it should be OK.

**Comment by Eren139** [comment]
> This is a warning from HF to indicate that the output exceeds the original context window length.
> 
> But if you check the output, it should be OK.

Token indices sequence length is longer than the specified maximum sequence length for this model (5592 > 4096). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/root/autodl-tmp/LaWGPT/utils/callbacks.py", line 47, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/root/autodl-tmp/LaWGPT/webui.py", line 140, in generate_with_callback
    model.generate(**kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/peft/peft_model.py", line 627, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 1596, in generate
    return self.greedy_search(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 2444, in greedy_search
    outputs = self(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 809, in forward
    outputs = self.model(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 697, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 413, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 335, in forward
    attn_weights = torch.matmul(query_states, key_states.transpose(2, 3)) / math.sqrt(self.head_dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.87 GiB (GPU 0; 23.65 GiB total capacity; 8.51 GiB already allocated; 1.05 GiB free; 8.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/root/autodl-tmp/LaWGPT/webui.py", line 156, in evaluate
    print(decoded_output)
UnboundLocalError: local variable 'decoded_output' referenced before assignment具体错误是这样的，我该如何对代码进行修改呢？谢谢！

**Comment by Mooler0410** [comment]
朋友，你这个主要是显存不大够的问题:
(torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.87 GiB (GPU 0; 23.65 GiB total capacity; 8.51 GiB already allocated; 1.05 GiB free; 8.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation)

(默认你跑的llama7b）有三个办法：
1: 如果你有两张24g的卡， 用deepspeed inference，应该能跑起来。
2: 如果只有一张卡，得等一下我等把flash attention的版本release。
3: 如果你有四张24g的卡，只用hugging face默认的accelerator的model parallel的方式，按理说能跑到8k附近。那问题可能是需要控制一下torch提前reserve的显存的大小，设置一下： PYTORCH_CUDA_ALLOC_CONF='max_split_size_mb:1024' ，1024就好了，更大一点或许也可以，会快一点。也就是这个问题 ( If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation)

**Comment by dengxiaotian123** [comment]
> PYTORCH_CUDA_ALLOC_CONF='max_split_size_mb:102
 我试了PYTORCH_CUDA_ALLOC_CONF='max_split_size_mb:1024' ，甚至更大的值，每次在length=15872的时候就OOM了
错误如下
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.03 GiB (GPU 1; 79.35 GiB total capacity; 48.80 GiB already allocated; 27.55 GiB free; 50.37 GiB             reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and        PYTORCH_CUDA_ALLOC_CONF`
