### ISSUE TITLE
Something wrong in modify_method_of_instance function

### ISSUE THREAD

**Issue by meizhen-nlp** [datamllab/LongLM#31]
Thanks for your code. I encountered the following issue while trying to extend the context length of Qwen1.5-14B-Chat. Do you know how I can fix this Exception? Many THX!

```python
Traceback (most recent call last):
  File "/***/envs/qwen/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/***/envs/qwen/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/***/Qwen1_5/longlm/LongLM/pred.py", line 63, in get_pred
    SelfExtend.apply(model, group_size, window_size, enable_flash_attention=use_flash, flash_attention_impl="flash_attn")
  File "/***/Qwen1_5/longlm/LongLM/SelfExtend.py", line 179, in apply
    raise Exception(f"Failed to modify the attention method of {arch_name}")
Exception: Failed to modify the attention method of Qwen2ForCausalLM
```
Under the setting of:   
  - transformers   4.38.2
  - flash-attn   2.5.5

**Comment by Mooler0410** [comment]
This Exception is for the case: the targeted instance has no designated attention module within it. It may caused by:
You load the model without flash attention but set enable_flash_attention = True, or the reverse case. 

If possible, you may check the attention module's name by simple print(model) before calling SelfExtend.apply

**Comment by meizhen-nlp** [comment]
Got it! THX!
